# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('api_url', models.CharField(max_length=500, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Valor Compra')),
                ('quant_compra', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Quantidade Compra')),
                ('valor_venda', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Valor Venda')),
                ('quant_venda', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Quantidade Venda')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange', to='monitor.Exchanges')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data|Hora')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Preço da compra')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Preço da venda')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Diferença (%)')),
                ('exchange_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange_Comprar', to='monitor.Exchanges')),
                ('exchange_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exchange_Vender', to='monitor.Exchanges')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-time'],
            },
        ),
    ]
